site_name: Documentation - The SERP Spider

site_url: https://serp-spider.github.io/documentation

pages:
  - Documentation:
    - Home: index.md
    - Overview: overview.md
    - Cookies: cookies.md

  - Search Engines:
    - Google: search-engine/google.md

  - Http Clients:
      - CURL: http-client/curl.md
      - PhantomJS: http-client/phantomJS.md
      - SpidyJS: http-client/spidyJS.md

  - About:
    - Packages: about/packages.md
    - Versions: about/versions.md

  - _hidden:
    - Parse a Google Page: search-engine/google/parse-page.md
    - Google Url: search-engine/google/google-url.md
    - Handle Google error: search-engine/google/handle-errors.md
    - Configure Google Client: search-engine/google/client-configuration.md
    - migration 0.2: about/migration/from-v0_1-to-v0_2.md

repo_url: https://github.com/serp-spider

theme_dir: 'themes/serps'

site_description: >
  SERPS is a SERP Scraper for php.
  It offers a set of tools to manipulate and parse popular search engines such as Google, Yahoo, Bing...

site_favicon: favicon.ico

google_analytics:
  - UA-75620778-1
  - serp-spider.github.io


markdown_extensions:
  - admonition